name: Build

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: cordiverse/workflows/.github/actions/setup@main

      - name: Lint JavaScript
        run: yarn build:all

